apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-12t8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qwsx-tenant/rhtap-demo-app/hacbs-test-project-12t8@sha256:b7c8e65854df3b9711dcaf50d2830384be5434aaf9b2599e3fd0cc16c05ac03e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
