apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-12t8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qwsx-tenant/rhtap-demo-app/hacbs-test-project-12t8@sha256:a812396b5195a66b642c12fddc6baff266aa546fa45504c19f79f41528713f6c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
