apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-12t8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qwsx-tenant/rhtap-demo-app/hacbs-test-project-12t8@sha256:0093dea5828e06b3ea1b9fe911ec8c86e3dc3062398d3559c5dcd9afe6460ed2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
